version: "3.4"

networks:
  jello:
    driver: bridge

services:

  jello_sqlserver_image:
    container_name: jello_sqlserver_image
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "3g5h165tsK65j1s564L69ka5R168kk37sut5ls3Sk2t"
      ACCEPT_EULA: "Y"
    restart: always
    networks:
      - jello
  jello:
    container_name: jello
    image: jello:latest
    depends_on:
      - "jello_sqlserver_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SQLSERVER_HOST: jello_sqlserver_image
    networks:
      - jello
volumes:
  sqlserver_db_volume:
