version: "3.4"

networks:
  kiko:
    driver: bridge

services:

  kiko_postgres_image:
    container_name: kiko_postgres_image
    image: postgres:11
    ports:
      - 5432
    restart: always
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "3g5h165tsK65j1s564L69ka5R168kk37sut5ls3Sk2t"
      POSTGRES_DB: "postgres"
    networks:
      - kiko

  kiko_mysql_image:
    container_name: kiko_mysql_image
    image: mysql:5.7
    command: mysqld
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 3g5h165tsK65j1s564L69ka5R168kk37sut5ls3Sk2t
      MYSQL_ROOT_PASSWORD: 3g5h165tsK65j1s564L69ka5R168kk37sut5ls3Sk2t
      MYSQL_DATABASE: keyhan
      MYSQL_USER: keyhan
      MYSQL_PASSWORD: 3g5h165tsK65j1s564L69ka5R168kk37sut5ls3Sk2t
    volumes:
      - mysql_db_volume:/var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - kiko
  kiko:
    container_name: kiko
    image: kiko:latest
    depends_on:
      - "kiko_postgres_image"
      - "kiko_mysql_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: kiko_postgres_image
      MYSQL_HOST: kiko_mysql_image
    networks:
      - kiko
volumes:
  postgres_db_volume:
  mysql_db_volume:
