version: "3.4"

networks:
  ateyetekoon:
    driver: bridge

services:
  ateyetekoon_mongodb_image:
    container_name: ateyetekoon_mongodb_image
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: aseman
      MONGO_INITDB_ROOT_PASSWORD: 3x2fG1b65sg4hN68sr4yj8j6k5Bstul4yi56l453tsK5346u5s4R648j
    ports:
      - 27017:2701
    restart: always
    networks:
      - ateyetekoon
  ateyetekoon:
    container_name: ateyetekoon
    image: ateyetekoon:latest
    depends_on:
      - "ateyetekoon_mongodb_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    environment:
      MONGODB_HOST: ateyetekoon_mongodb_image
    networks:
      - ateyetekoon
volumes:
  mongodb_db_volume:
