version: "3.4"

networks:
  atefejoon:
    driver: bridge

services:
  atefejoon_mongodb_image:
    container_name: atefejoon_mongodb_image
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: aseman
      MONGO_INITDB_ROOT_PASSWORD: 3x2fG1b65sg4hN68sr4yj8j6k5Bstul4yi56l453tsK5346u5s4R648j
    restart: always
    networks:
      - atefejoon
  atefejoon:
    container_name: atefejoon
    image: atefejoon:latest
    depends_on:
      - "atefejoon_mongodb_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    environment:
      MONGODB_HOST: atefejoon_mongodb_image
    networks:
      - atefejoon
volumes:
  mongodb_db_volume:
