version: "3.4"

networks:
  ohyeamm:
    driver: bridge

services:

  ohyeamm_sqlserver_image:
    container_name: ohyeamm_sqlserver_image
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "3g5h165tsK65j1s564L69ka5R168kk37sut5ls3Sk2t"
      ACCEPT_EULA: "Y"
    restart: always
    networks:
      - ohyeamm
  ohyeamm:
    container_name: ohyeamm
    image: ohyeamm:latest
    depends_on:
      - "ohyeamm_sqlserver_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SQLSERVER_HOST: ohyeamm_sqlserver_image
    networks:
      - ohyeamm
volumes:
  sqlserver_db_volume:
