version: "3.4"

networks:
  doll:
    driver: bridge

services:
  doll_mongodb_image:
    container_name: doll_mongodb_image
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: aseman
      MONGO_INITDB_ROOT_PASSWORD: 3x2fG1b65sg4hN68sr4yj8j6k5Bstul4yi56l453tsK5346u5s4R648j
    ports:
      - 27017:27017
    restart: always
    networks:
      - doll
  doll:
    container_name: doll
    image: doll:latest
    depends_on:
      - "doll_mongodb_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    environment:
      MONGODB_HOST: doll_mongodb_image
    networks:
      - doll
volumes:
  mongodb_db_volume:
