version: "3.4"

networks:
  atefehonkeyhan:
    driver: bridge

services:
  atefehonkeyhan_mongodb_image:
    container_name: atefehonkeyhan_mongodb_image
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: aseman
      MONGO_INITDB_ROOT_PASSWORD: 3x2fG1b65sg4hN68sr4yj8j6k5Bstul4yi56l453tsK5346u5s4R648j
    restart: always
    networks:
      - atefehonkeyhan
  atefehonkeyhan:
    container_name: atefehonkeyhan
    image: atefehonkeyhan:latest
    depends_on:
      - "atefehonkeyhan_mongodb_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      MONGODB_HOST: atefehonkeyhan_mongodb_image
    networks:
      - atefehonkeyhan
volumes:
  mongodb_db_volume:
