version: "3.4"

networks:
  atefehkoon:
    driver: bridge

services:
  atefehkoon_mongodb_image:
    container_name: atefehkoon_mongodb_image
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: aseman
      MONGO_INITDB_ROOT_PASSWORD: 3x2fG1b65sg4hN68sr4yj8j6k5Bstul4yi56l453tsK5346u5s4R648j
    restart: always
    networks:
      - atefehkoon
  atefehkoon:
    container_name: atefehkoon
    image: atefehkoon:latest
    depends_on:
      - "atefehkoon_mongodb_image"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGODB_HOST: atefehkoon_mongodb_image
    networks:
      - atefehkoon
volumes:
  mongodb_db_volume:
