version: "3.4"

networks:
  loveatefeeh:
    driver: bridge

services:

  loveatefeeh_sqlserver_image:
    container_name: loveatefeeh_sqlserver_image
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "3g5h165tsK65j1s564L69ka5R168kk37sut5ls3Sk2t"
      ACCEPT_EULA: "Y"
    restart: always
    networks:
      - loveatefeeh
  loveatefeeh:
    container_name: loveatefeeh
    image: loveatefeeh:latest
    depends_on:
      - "loveatefeeh_sqlserver_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SQLSERVER_HOST: loveatefeeh_sqlserver_image
    networks:
      - loveatefeeh
volumes:
  sqlserver_db_volume:
