version: "3.4"

networks:
  merikoon:
    driver: bridge

services:
  merikoon_mongodb_image:
    container_name: merikoon_mongodb_image
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: aseman
      MONGO_INITDB_ROOT_PASSWORD: 3x2fG1b65sg4hN68sr4yj8j6k5Bstul4yi56l453tsK5346u5s4R648j
    ports:
      - 27017:27017
    restart: always
    networks:
      - merikoon
  merikoon:
    container_name: merikoon
    image: merikoon:latest
    depends_on:
      - "merikoon_mongodb_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    environment:
      MONGODB_HOST: merikoon_mongodb_image
    networks:
      - merikoon
volumes:
  mongodb_db_volume:
