version: "3.4"

networks:
  ahah:
    driver: bridge

services:

  ahah_sqlserver_image:
    container_name: ahah_sqlserver_image
    image: "mcr.microsoft.com/mssql/server"
    environment:
    SA_PASSWORD: "3g5h165tsK65j1s564L69ka5R168kk37sut5ls3Sk2t"
    ACCEPT_EULA: "Y"
    restart: always
    networks:
      - ahah
  ahah:
    container_name: ahah
    image: ahah:latest
    depends_on:
      - "ahah_sqlserver_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SQLSERVER_HOST: ahah_sqlserver_image
    networks:
      - ahah
volumes:
  sqlserver_db_volume:
