version: "3.4"

networks:
  dokopol:
    driver: bridge

services:
  dokopol_mongodb_image:
    container_name: dokopol_mongodb_image
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: aseman
      MONGO_INITDB_ROOT_PASSWORD: 3x2fG1b65sg4hN68sr4yj8j6k5Bstul4yi56l453tsK5346u5s4R648j
    ports:
      - 27017:27017
    restart: always
    networks:
      - dokopol
  dokopol:
    container_name: dokopol
    image: dokopol:latest
    depends_on:
      - "dokopol_mongodb_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    environment:
      MONGODB_HOST: dokopol_mongodb_image
    networks:
      - dokopol
volumes:
  mongodb_db_volume:
