version: "3.4"

networks:
  bokon:
    driver: bridge

services:
  bokon_mongodb_image:
    container_name: bokon_mongodb_image
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: aseman
      MONGO_INITDB_ROOT_PASSWORD: 3x2fG1b65sg4hN68sr4yj8j6k5Bstul4yi56l453tsK5346u5s4R648j
    ports:
      - 27017:27017
    restart: always
    networks:
      - bokon
  bokon:
    container_name: bokon
    image: bokon:latest
    depends_on:
      - "bokon_mongodb_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    environment:
      MONGODB_HOST: bokon_mongodb_image
    networks:
      - bokon
volumes:
  mongodb_db_volume:
