version: "3.4"

networks:
  dockertest:
    driver: bridge

services:

  dockertest_postgres_image:
    container_name: dockertest_postgres_image
    image: postgres:11
    ports:
      - 5432
    restart: always
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "3g5h165tsK65j1s564L69ka5R168kk37sut5ls3Sk2t"
      POSTGRES_DB: "postgres"
    networks:
      - dockertest

  dockertest_mysql_image:
    container_name: dockertest_mysql_image
    image: mysql:5.7
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 3g5h165tsK65j1s564L69ka5R168kk37sut5ls3Sk2t
      MYSQL_ROOT_PASSWORD: 3g5h165tsK65j1s564L69ka5R168kk37sut5ls3Sk2t
      MYSQL_DATABASE: keyhan
      MYSQL_USER: keyhan
      MYSQL_PASSWORD: 3g5h165tsK65j1s564L69ka5R168kk37sut5ls3Sk2t
    volumes:
      - mysql_db_volume:/var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - dockertest
  dockertest:
    container_name: dockertest
    image: dockertest:latest
    depends_on:
      - "dockertest_postgres_image"
      - "dockertest_mysql_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: dockertest_postgres_image
      MYSQL_HOST: dockertest_mysql_image
    networks:
      - dockertest
volumes:
  postgres_db_volume:
  mysql_db_volume:
