version: "3.4"

networks:
  tookoseatefeh:
    driver: bridge

services:
  tookoseatefeh_mongodb_image:
    container_name: tookoseatefeh_mongodb_image
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: aseman
      MONGO_INITDB_ROOT_PASSWORD: 3x2fG1b65sg4hN68sr4yj8j6k5Bstul4yi56l453tsK5346u5s4R648j
    restart: always
    networks:
      - tookoseatefeh
  tookoseatefeh:
    container_name: tookoseatefeh
    image: tookoseatefeh:latest
    depends_on:
      - "tookoseatefeh_mongodb_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    environment:
      MONGODB_HOST: tookoseatefeh_mongodb_image
    networks:
      - tookoseatefeh
volumes:
  mongodb_db_volume:
