version: "3.4"

networks:
  atefehkos:
    driver: bridge

services:
  atefehkos_mongodb_image:
    container_name: atefehkos_mongodb_image
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: aseman
      MONGO_INITDB_ROOT_PASSWORD: 3x2fG1b65sg4hN68sr4yj8j6k5Bstul4yi56l453tsK5346u5s4R648j
    restart: always
    networks:
      - atefehkos
  atefehkos:
    container_name: atefehkos
    image: atefehkos:latest
    depends_on:
      - "atefehkos_mongodb_image"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGODB_HOST: atefehkos_mongodb_image
    networks:
      - atefehkos
volumes:
  mongodb_db_volume:
