version: "3.4"

networks:
  mmyeah:
    driver: bridge

services:

  mmyeah_sqlserver_image:
    container_name: mmyeah_sqlserver_image
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "3g5h165tsK65j1s564L69ka5R168kk37sut5ls3Sk2t"
      ACCEPT_EULA: "Y"
    restart: always
    networks:
      - mmyeah
  mmyeah:
    container_name: mmyeah
    image: mmyeah:latest
    depends_on:
      - "mmyeah_sqlserver_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SQLSERVER_HOST: mmyeah_sqlserver_image
    networks:
      - mmyeah
volumes:
  sqlserver_db_volume:
