version: "3.4"

networks:
  atkos:
    driver: bridge

services:
  atkos_mongodb_image:
    container_name: atkos_mongodb_image
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: aseman
      MONGO_INITDB_ROOT_PASSWORD: 3x2fG1b65sg4hN68sr4yj8j6k5Bstul4yi56l453tsK5346u5s4R648j
    ports:
      - 27017:2701
    restart: always
    networks:
      - atkos
  atkos:
    container_name: atkos
    image: atkos:latest
    depends_on:
      - "atkos_mongodb_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    environment:
      MONGODB_HOST: atkos_mongodb_image
    networks:
      - atkos
volumes:
  mongodb_db_volume:
